

// role_name, org_id, require_license, description, role_type, active,
// extended_roles, created_at, updated_at, is_default, assignable,
// scope, permissions_summary, role_level, tags

const defaultRoles = {
    "standard Roles": [
        {
            role_name: 'End User / Requester',
            org_id: 'default',
            require_license: 'false',
            description: 'Employees or customers using the service portal.',
            role_type: 'global',
            active: 1,
            extended_roles: 'false',
            created_at: 'CURRENT_TIMESTAMP',
            updated_at: 'CURRENT_TIMESTAMP',
            is_default: 1,
            assignable: 1,
            scope: 'All',
            permissions_summary: '{"access":"self-service"}',
            role_level: 1,
            tags: '["basic","request"]'
        },
        {
            role_name: 'Service Desk Agent',
            org_id: 'default',
            require_license: 'true',
            description: 'First-line support staff handling tickets and routing.',
            role_type: 'global',
            active: 1,
            extended_roles: 'false',
            created_at: 'CURRENT_TIMESTAMP',
            updated_at: 'CURRENT_TIMESTAMP',
            is_default: 1,
            assignable: 1,
            scope: 'IT',
            permissions_summary: '{"access":"tickets, escalation"}',
            role_level: 2,
            tags: '["support","agent"]'
        },
        {
            role_name: 'Service Owner',
            org_id: 'default',
            require_license: 'false',
            description: 'Accountable for a specific service lifecycle.',
            role_type: 'global',
            active: 1,
            extended_roles: 'false',
            created_at: 'CURRENT_TIMESTAMP',
            updated_at: 'CURRENT_TIMESTAMP',
            is_default: 1,
            assignable: 1,
            scope: 'All',
            permissions_summary: '{"access":"service definition, reports"}',
            role_level: 4,
            tags: '["service","owner"]'
        },
        {
            role_name: 'Process Owner',
            org_id: 'default',
            require_license: 'false',
            description: 'Owns and improves ESM processes.',
            role_type: 'global',
            active: 1,
            extended_roles: 'false',
            created_at: 'CURRENT_TIMESTAMP',
            updated_at: 'CURRENT_TIMESTAMP',
            is_default: 1,
            assignable: 1,
            scope: 'All',
            permissions_summary: '{"access":"process design, kpi"}',
            role_level: 4,
            tags: '["process","management"]'
        },
        {
            role_name: 'Configuration Manager',
            org_id: 'default',
            require_license: 'false',
            description: 'Maintains CMDB data and relationships.',
            role_type: 'global',
            active: 1,
            extended_roles: 'false',
            created_at: 'CURRENT_TIMESTAMP',
            updated_at: 'CURRENT_TIMESTAMP',
            is_default: 1,
            assignable: 1,
            scope: 'IT',
            permissions_summary: '{"access":"CMDB, impact analysis"}',
            role_level: 3,
            tags: '["cmdb","ci"]'
        },
        {
            role_name: 'Change Manager',
            org_id: 'default',
            require_license: 'false',
            description: 'Manages change approvals and CAB.',
            role_type: 'global',
            active: 1,
            extended_roles: 'false',
            created_at: 'CURRENT_TIMESTAMP',
            updated_at: 'CURRENT_TIMESTAMP',
            is_default: 1,
            assignable: 1,
            scope: 'IT',
            permissions_summary: '{"access":"change evaluation, CAB"}',
            role_level: 3,
            tags: '["change","approval"]'
        },
        {
            role_name: 'Knowledge Manager',
            org_id: 'default',
            require_license: 'false',
            description: 'Maintains the knowledge base.',
            role_type: 'global',
            active: 1,
            extended_roles: 'false',
            created_at: 'CURRENT_TIMESTAMP',
            updated_at: 'CURRENT_TIMESTAMP',
            is_default: 1,
            assignable: 1,
            scope: 'All',
            permissions_summary: '{"access":"knowledge creation"}',
            role_level: 2,
            tags: '["knowledge","content"]'
        },
        {
            role_name: 'Administrator',
            org_id: 'default',
            require_license: 'true',
            description: 'Administers the ESM platform.',
            role_type: 'global',
            active: 1,
            extended_roles: 'false',
            created_at: 'CURRENT_TIMESTAMP',
            updated_at: 'CURRENT_TIMESTAMP',
            is_default: 1,
            assignable: 1,
            scope: 'IT',
            permissions_summary: '{"access":"admin, config, upgrade"}',
            role_level: 5,
            tags: '["platform","admin"]'
        },
        {
            role_name: 'Reporting and Analytics Specialist',
            org_id: 'default',
            require_license: 'false',
            description: 'Handles metrics and service reports.',
            role_type: 'global',
            active: 1,
            extended_roles: 'false',
            created_at: 'CURRENT_TIMESTAMP',
            updated_at: 'CURRENT_TIMESTAMP',
            is_default: 1,
            assignable: 1,
            scope: 'All',
            permissions_summary: '{"access":"analytics, dashboard"}',
            role_level: 3,
            tags: '["analytics","sla"]'
        },
        {
            role_name: 'Business Owner',
            org_id: 'default',
            require_license: 'false',
            description: 'Department leader using ESM.',
            role_type: 'global',
            active: 1,
            extended_roles: 'false',
            created_at: 'CURRENT_TIMESTAMP',
            updated_at: 'CURRENT_TIMESTAMP',
            is_default: 1,
            assignable: 1,
            scope: 'All',
            permissions_summary: '{"access":"service quality, department input"}',
            role_level: 4,
            tags: '["business","owner"]'
        },
        {
            role_name: 'Product Manager',
            org_id: 'default',
            require_license: 'false',
            description: 'Owns ESM tool as a product.',
            role_type: 'global',
            active: 1,
            extended_roles: 'false',
            created_at: 'CURRENT_TIMESTAMP',
            updated_at: 'CURRENT_TIMESTAMP',
            is_default: 1,
            assignable: 1,
            scope: 'All',
            permissions_summary: '{"access":"product roadmap, adoption"}',
            role_level: 5,
            tags: '["product","strategy"]'
        }
    ],
    "Enhanced Roles": [
        {
            role_name: 'Catalogue Manager',
            org_id: 'default',
            require_license: 'false',
            description: 'Manages the enterprise service catalog.',
            role_type: 'global',
            active: 1,
            extended_roles: 'true',
            created_at: 'CURRENT_TIMESTAMP',
            updated_at: 'CURRENT_TIMESTAMP',
            is_default: 1,
            assignable: 1,
            scope: 'All',
            permissions_summary: '{"access":"catalog, service value"}',
            role_level: 4,
            tags: '["catalog","portfolio"]'
        },
        {
            role_name: 'Form Designer',
            org_id: 'default',
            require_license: 'false',
            description: 'Designs intuitive service portals.',
            role_type: 'local',
            active: 1,
            extended_roles: 'true',
            created_at: 'CURRENT_TIMESTAMP',
            updated_at: 'CURRENT_TIMESTAMP',
            is_default: 1,
            assignable: 1,
            scope: 'UX',
            permissions_summary: '{"access":"form design, UI"}',
            role_level: 2,
            tags: '["ux","form"]'
        },
        {
            role_name: 'Flow Builder',
            org_id: 'default',
            require_license: 'false',
            description: 'Creates workflows to automate service delivery.',
            role_type: 'local',
            active: 1,
            extended_roles: 'true',
            created_at: 'CURRENT_TIMESTAMP',
            updated_at: 'CURRENT_TIMESTAMP',
            is_default: 1,
            assignable: 1,
            scope: 'IT',
            permissions_summary: '{"access":"workflow builder"}',
            role_level: 3,
            tags: '["automation","workflow"]'
        },
        {
            role_name: 'Integration Specialist',
            org_id: 'default',
            require_license: 'true',
            description: 'Manages integrations with external systems.',
            role_type: 'global',
            active: 1,
            extended_roles: 'true',
            created_at: 'CURRENT_TIMESTAMP',
            updated_at: 'CURRENT_TIMESTAMP',
            is_default: 1,
            assignable: 1,
            scope: 'IT',
            permissions_summary: '{"access":"integrations, APIs"}',
            role_level: 4,
            tags: '["integration","api"]'
        },
        {
            role_name: 'Security and Compliance Officer',
            org_id: 'default',
            require_license: 'true',
            description: 'Ensures data privacy and platform compliance.',
            role_type: 'global',
            active: 1,
            extended_roles: 'true',
            created_at: 'CURRENT_TIMESTAMP',
            updated_at: 'CURRENT_TIMESTAMP',
            is_default: 1,
            assignable: 1,
            scope: 'Security',
            permissions_summary: '{"access":"audit, compliance"}',
            role_level: 5,
            tags: '["security","compliance"]'
        },
        {
            role_name: 'DevOps Engineer',
            org_id: 'default',
            require_license: 'true',
            description: 'Supports ESM in DevOps environments.',
            role_type: 'global',
            active: 1,
            extended_roles: 'true',
            created_at: 'CURRENT_TIMESTAMP',
            updated_at: 'CURRENT_TIMESTAMP',
            is_default: 1,
            assignable: 1,
            scope: 'IT',
            permissions_summary: '{"access":"CI/CD, infra"}',
            role_level: 4,
            tags: '["devops","ci"]'
        },
        {
            role_name: 'Trainer',
            org_id: 'default',
            require_license: 'false',
            description: 'Drives adoption through training.',
            role_type: 'local',
            active: 1,
            extended_roles: 'true',
            created_at: 'CURRENT_TIMESTAMP',
            updated_at: 'CURRENT_TIMESTAMP',
            is_default: 1,
            assignable: 1,
            scope: 'All',
            permissions_summary: '{"access":"training, comms"}',
            role_level: 2,
            tags: '["training","adoption"]'
        },
        {
            role_name: 'Quality Engineer',
            org_id: 'default',
            require_license: 'false',
            description: 'Ensures data accuracy in CMDB and requests.',
            role_type: 'local',
            active: 1,
            extended_roles: 'true',
            created_at: 'CURRENT_TIMESTAMP',
            updated_at: 'CURRENT_TIMESTAMP',
            is_default: 1,
            assignable: 1,
            scope: 'IT',
            permissions_summary: '{"access":"data quality"}',
            role_level: 3,
            tags: '["quality","cmdb"]'
        },
        {
            role_name: 'Approver',
            org_id: 'default',
            require_license: 'false',
            description: 'Designated person to approve requests.',
            role_type: 'private',
            active: 1,
            extended_roles: 'true',
            created_at: 'CURRENT_TIMESTAMP',
            updated_at: 'CURRENT_TIMESTAMP',
            is_default: 1,
            assignable: 1,
            scope: 'All',
            permissions_summary: '{"access":"approval"}',
            role_level: 3,
            tags: '["approver","policy"]'
        },
        {
            role_name: 'Reviewer',
            org_id: 'default',
            require_license: 'false',
            description: 'SME reviewing requests before approval.',
            role_type: 'private',
            active: 1,
            extended_roles: 'true',
            created_at: 'CURRENT_TIMESTAMP',
            updated_at: 'CURRENT_TIMESTAMP',
            is_default: 1,
            assignable: 1,
            scope: 'All',
            permissions_summary: '{"access":"review"}',
            role_level: 2,
            tags: '["review","validation"]'
        }
    ]
}