const EventFields = [
  {
    type: "input",
    name: "id",
    label: "ID",
    contentType: "number",
    placeholder: "Enter ID",
    customStyles: {},
    isMandatory: true,
  },
  {
    type: "input",
    name: "source",
    label: "Source",
    contentType: "string",
    placeholder: "Enter Source",
    customStyles: {},
    isMandatory: true,
  },
  {
    type: "input",
    name: "user_id",
    label: "User ID",
    contentType: "number",
    placeholder: "Enter User ID",
    customStyles: {},
    isMandatory: true,
  },
  {
    type: "input",
    name: "ip_address",
    label: "IP Address",
    contentType: "string",
    placeholder: "Enter IP Address",
    customStyles: {},
    isMandatory: true,
  },
  {
    type: "input",
    name: "title",
    label: "Title",
    contentType: "string",
    placeholder: "Enter Title",
    customStyles: {},
    isMandatory: true,
  },
  {
    type: "input",
    name: "timestamp",
    label: "Timestamp",
    contentType: "datetime",
    placeholder: "Select Timestamp",
    customStyles: {},
    isMandatory: true,
  },
  {
    type: "input",
    name: "component_name",
    label: "Component Name",
    contentType: "string",
    placeholder: "Enter Component Name",
    customStyles: {},
    isMandatory: true,
  },
  {
    type: "dropdown",
    name: "type",
    label: "Type",
    contentType: "enum",
    placeholder: "Select Type",
    customStyles: {},
    isMandatory: true,
    options: [
      { label: "Option 1", value: "option_1" },
      { label: "Option 2", value: "option_2" },
    ],
  },
  {
    type: "dropdown",
    name: "active",
    label: "Active",
    contentType: "enum",
    placeholder: "Select Status",
    customStyles: {},
    isMandatory: true,
    options: [
      { label: "Yes", value: "yes" },
      { label: "No", value: "no" },
    ],
  },
  {
    type: "input",
    name: "page_url",
    label: "Page URL",
    contentType: "string",
    placeholder: "Enter Page URL",
    customStyles: {},
    isMandatory: true,
  },
  {
    type: "input",
    name: "session_id",
    label: "Session ID",
    contentType: "string",
    placeholder: "Enter Session ID",
    customStyles: {},
    isMandatory: true,
  },
  {
    type: "input",
    name: "user_agent",
    label: "User Agent",
    contentType: "string",
    placeholder: "Enter User Agent",
    customStyles: {},
    isMandatory: true,
  },
  {
    type: "dropdown",
    name: "category",
    label: "Category",
    contentType: "enum",
    placeholder: "Select Category",
    customStyles: {},
    isMandatory: true,
    options: [
      { label: "A", value: "A" },
      { label: "B", value: "B" },
    ],
  },
];

module.exports = EventFields;
