
const DepartmentsData = {
  "Global": {
    "Core Forms": ["User Form", "Groups Form", "Companies Form", "Roles Form", "Locations Form", "Departments Form", "Connections Form",],
    "Extended Forms": ["Notifications Form", "Alerts Form", "Feedbacks Form",],
    "CMDB Forms": ["CMDB Form",]
  },
  "Finance": {
    "Financial Planning": ["Financial Planning"],
    "Audit": ["Audit"],
    "Accounts": ["Payable", "Accountant"],
    "Investment": ["Investment"],
    "Controls": ["Internal Controls", "External Controls", "Global Controls"],
    "Tax": ["Tax"],
    "Corporation": ["Corporate Finance", "Corporate Action"],
    "Payroll": ["Payroll"],
    "Risk Management": ["Risk Management"],
    "Investments": ["Investments"],
    "Book Keeping": ["Book Keeping"],
    "Treasure": ["Treasure"],
    "Budgeting": ["Budgeting"],
    "CFO": ["CFO"]
  },
  "Human Resources": {
    "Compensation and Benefits": ["Employee Benefits", "Employee Engagement"],
    "Health and Safety": ["Health and Safety"],
    "Training and Development": ["Employee Development", "Career Planning"],
    "Compliance": ["HR Information Systems"],
    "Labor Relations": ["Labor Relations"],
    "Policies": ["Policies"],
    "Business Administration": ["HR Planning", "HR Assistant", "Organization"],
    "Talent Management": ["Recruitment"],
    "Employee Lifecycle Events": ["Onboard", "Offboard", "CrossBoard"],
    "Payroll": ["Payroll"],
    "General": ["Record Management"]
  },
  "IT": {
    "Security": ["Security"],
    "Cloud Management": ["Cloud Management"],
    "Analytics": ["Analytics"],
    "Support": ["Support"],
    "Application Management": ["Web Development", "Architecture", "Programming"],
    "Network Administration": ["Network Administration"],
    "Business Administration": ["Business Administration"]
  },
  "Operations": {
    "Inventory": ["Inventory"],
    "Analytics": ["Analytics"],
    "Quality Management": ["Quality Management"],
    "Delivery Management": ["Delivery Management"],
    "Process": ["Process Improvement"],
    "PMO": ["Architecture"]
  },
  "Research & Development": {
    "Basic Research": ["Basic Research"],
    "Applied Research": ["Applied Research"],
    "Experimental Development": ["Experimental Development"]
  },
  "Sales": {
    "Business Development": ["Promotions"],
    "Sales Management": ["Inside Sales", "VP of Sales", "Regional Sales", "Outside Sales"],
    "Client Management": ["Pre-Sales", "Post Sales"],
    "General": ["General"]
  },
  "Security": {
    "International Security": ["International Security"],
    "Application Security": ["Application Security"],
    "Physical Security": ["Physical Security"],
    "Endpoint Security": ["Endpoint Security"],
    "Bank Security": ["Bank Security"],
    "Cloud Security": ["Cloud Security"],
    "Information Security": ["Information Security"],
    "Security Consultant": ["Security Consultant"],
    "Brand Protection": ["Brand Protection"],
    "Video Surveillance": ["Video Surveillance"],
    "Bodyguard": ["Security Guard", "Contract Security Guards"],
    "Security Management": ["Security Management"],
    "SPG Level Security": ["SPG Level Security"]
  },
  "Logistics": {
    "Inventory Management": ["Supply chain Management", "Inventory Analyst"],
    "Transportation": ["Outbound Transportation"],
    "Warehousing": ["Warehouse Manager"],
    "Third Party and Fourth Party Logistics": ["Third Party Logistics Services", "Outbound Logistics", "Reverse Logistics", "Inbound Logistics", "Logistics Coordinator", "Branch Logistics"],
    "Distribution": ["Distribution"],
    "Packaging": ["Packaging"],
    "Procurement": ["Procurement"],
    "Customer Service": ["Customer Service"],
    "Demand Planner": ["Demand Planner"],
    "Material Handling": ["Material Handling"],
    "Monitoring": ["Monitoring"],
    "Freight Forwarding": ["Freight Forwarding"],
    "Information Systems": ["Information Systems"],
    "Order Accuracy": ["Order Accuracy"]
  },
  "Dispatch": {
    "Transportation": ["Delivery Services", "Public Transit", "Logistics"],
    "Emergency Services": ["Police", "Fire", "Medical"],
    "Services": ["Maintenance", "Repair"],
    "Manufacturing": ["Delivery Services", "Public Transit", "Logistics"]
  },
  "Stores": {
    "Department Stores": ["Department Stores"],
    "Specialty Stores": ["Specialty Stores"],
    "Chain Stores": ["Chain Stores"],
    "Discount Stores": ["Discount Stores"],
    "Boutiques": ["Boutiques"],
    "Supermarkets": ["Supermarkets"],
    "Convenience Stores": ["Convenience Stores"],
    "Pop-Up Stores": ["Pop-Up Stores"],
    "E-Commerce Stores": ["E-Commerce Stores"],
    "Warehouse Retailers": ["Warehouse Retailers"],
    "Franchises": ["Franchises"],
    "Malls and Shopping Centers": ["Malls and Shopping Centers"],
    "Online Retailing": ["Online Retailing"],
    "Catalogue Retailing": ["Catalogue Retailing"],
    "Nonstore Retailing": ["Nonstore Retailing"]
  },
  "Marketing": {
    "Content Marketing": ["Content Marketing"],
    "Digital Marketing": ["Digital Marketing"],
    "Product Marketing": ["Product Marketing"],
    "Growth Marketing": ["Growth Marketing"],
    "Influencer Marketing": ["Influencer Marketing"],
    "Social Media Manager": ["Brand Manager"],
    "Marketing President": ["Marketing Manager", "Market Research", "Marketing Assistant", "Marketing Director", "Marketing Coordinator"],
    "Search Engine Marketing": ["Search Engine Optimization"],
    "Brand Strategist": ["Brand Strategist"],
    "Analyst": ["Analyst"],
    "Events": ["Events"],
    "Advertising Specialist": ["Advertising Specialist"],
    "Copywriting": ["Copywriting"],
    "Email Developer": ["Email Developer"],
    "Web Designer": ["Graphic Designer"],
    "Public Relations": ["Public Relations"]
  },
  "Product / Service Development": {
    "New to the Company": ["New to the Company"],
    "Improvement of Existing Product": ["Improvement of Existing Product"],
    "Extension of Product Line": ["Extension of Product Line"],
    "New to the Market": ["New to the Market"]
  },
  "Inspection": {
    "Pre Production Inspection": ["Pre Production Inspection"],
    "During Production Inspection": ["During Production Inspection"],
    "Pre Shipment Inspection": ["Pre Shipment Inspection"],
    "Container Loading/Unloading Inspection": ["Container Loading/Unloading Inspection"]
  },
  "PMO": {
    "Supportive PMO": ["Supportive PMO"],
    "Directive PMO": ["Directive PMO"],
    "Activist PMO": ["Activist PMO"],
    "Delivery PMO": ["Delivery PMO"],
    "Departmental PMO": ["Departmental PMO"],
    "Project": ["Project Management Training", "Project Governance", "Project Office", "Project Controllers", "Project Planners", "Project Support Officer"],
    "Portfolio Management Office": ["Portfolio Management Office"],
    "Program Management Office": ["Program Management Office"],
    "Strategic Planning": ["Strategic Planning"],
    "Resource Management": ["Resource Management"],
    "Governance": ["Governance"]
  },
  "Design": {
    "Graphic Design": ["Graphic Design"],
    "Interface Design": ["Interface Design"],
    "Packaging Design": ["Packaging Design"],
    "Product Design": ["Product Design"],
    "Game Design": ["Game Design"],
    "Publication Design": ["Publication Design"],
    "Interaction Design": ["Interaction Design"],
    "Landscape Design": ["Landscape Design"],
    "Interior Design": ["Interior Designer"],
    "Furniture Design": ["Furniture Design"],
    "Motion Graphic Design": ["Motion Graphic Design"],
    "Designer": ["Animation Designer", "Web Designer", "Experiential Designer", "UX Designer"],
    "Corporate": ["Corporate Identity"],
    "Advertising": ["Advertising"],
    "Illustration": ["Illustration"],
    "Architectural": ["Architectural"],
    "Industrial": ["Industrial"],
    "Art Director": ["Art Director"]
  },
  "Quality": {
    "Quality Planning": ["Quality Planning"],
    "Quality Assurance": ["Quality Assurance"],
    "Quality Control": ["Quality Control"],
    "Quality Improvement": ["Quality Improvement"],
    "Quality Management": ["Quality Management"]
  },
  "Maintenance": {
    "Preventive Maintenance": ["Preventive Maintenance"],
    "Predictive Maintenance": ["Predictive Maintenance"],
    "Condition Based Maintenance": ["Condition Based Maintenance"],
    "Corrective Maintenance": ["Corrective Maintenance"],
    "Emergency Maintenance": ["Emergency Maintenance"],
    "Run to-Failure Maintenance": ["Run to-Failure Maintenance"],
    "Planned Maintenance": ["Planned Maintenance"],
    "Reactive Maintenance": ["Reactive Maintenance"],
    "Routine Maintenance": ["Routine Maintenance"],
    "Predetermined Maintenance": ["Predetermined Maintenance"],
    "Total Productive Maintenance": ["Total Productive Maintenance"],
    "Improve Reliability": ["Improve Reliability"],
    "Maintenance Strategy": ["Maintenance Strategy"],
    "Maintenance Supervisors": ["Maintenance Supervisors"],
    "Employee Benefits": ["Employee Benefits"],
    "Prescriptive": ["Prescriptive"]
  },
  "Production": {
    "Batch Production": ["Batch Production"],
    "Continuous Production": ["Continuous Production"],
    "Flow Production": ["Flow Production"],
    "Custom Production": ["Custom Production"]
  },
  "Accounting": {
    "Tax Accounting": ["Tax Accounting"],
    "Financial Accounting": ["Financial Accounting"],
    "Management Accounting": ["Management Accounting"],
    "Cost Accounting": ["Cost Accounting"],
    "Forensic Accounting": ["Forensic Accounting"],
    "Governmental Accounting": ["Governmental Accounting"],
    "International Accounting": ["International Accounting"]
  },
  "Customer Service": {
    "Live Chat Support": ["Live Chat Support"],
    "Email Support": ["Email Support"],
    "Self-Service Support": ["Self-Service Support"],
    "Interactive Voice Support": ["Interactive Voice Support"],
    "Social Media Support": ["Social Media Support"],
    "Web Commerce Support": ["Web Commerce Support"],
    "On-site Support": ["On-site Support"],
    "Telephone Support": ["Telephone Support"]
  },
  "Business Administration": {
    "Human Resources": ["Human Resources"],
    "Finance": ["Finance"],
    "Accounting": ["Accounting"],
    "Operations Management": ["Operations Management"],
    "International Business": ["International Business"],
    "Marketing Manager": ["Marketing Manager"],
    "Entrepreneurship": ["Entrepreneurship"],
    "Management": ["Management"],
    "Project Management": ["Project Management"],
    "Sales": ["Sales"],
    "Business Foundations": ["Business Foundations"],
    "Health Administration": ["Health Administration"],
    "IT Management": ["IT Management"],
    "Logistics": ["Logistics Analyst"],
    "Business Communications": ["Business Communications"],
    "Business Ethics": ["Business Ethics"],
    "Corporate Finance": ["Corporate Finance"],
    "Economics": ["Economics"],
    "Leadership": ["Leadership"],
    "Management Consultant": ["Management Consultant"],
    "Marketing": ["Marketing"],
    "Consultants": ["Consultants"],
    "Analysis of Theory": ["Analysis of Theory"]
  }
}

module.exports = { DepartmentsData }